# Generated by Django 3.2 on 2021-04-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('value_per_mounth', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
